# Generated by Django 2.1.2 on 2020-08-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_administer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('protocol_type', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('wrong_fragment', models.IntegerField()),
                ('urgent', models.IntegerField()),
                ('hot', models.IntegerField()),
                ('num_failed_logins', models.IntegerField()),
                ('logged_in', models.IntegerField()),
                ('num_root', models.IntegerField()),
                ('root_shell', models.IntegerField()),
                ('is_guest_login', models.IntegerField()),
                ('count', models.IntegerField()),
                ('srv_count', models.IntegerField()),
                ('diff_srv_rate', models.CharField(max_length=255)),
                ('srv_diff_host_rate', models.CharField(max_length=255)),
                ('dst_host_count', models.IntegerField()),
                ('dst_host_srv_count', models.IntegerField()),
                ('dst_host_same_srv_rate', models.CharField(max_length=255)),
                ('dst_host_diff_srv_rate', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'predict_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TraceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('protocol_type', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.CharField(max_length=255)),
                ('wrong_fragment', models.IntegerField()),
                ('urgent', models.IntegerField()),
                ('hot', models.IntegerField()),
                ('num_failed_logins', models.IntegerField()),
                ('logged_in', models.IntegerField(blank=True, null=True)),
                ('num_root', models.IntegerField()),
                ('root_shell', models.IntegerField(blank=True, null=True)),
                ('is_guest_login', models.IntegerField()),
                ('count', models.IntegerField()),
                ('srv_count', models.IntegerField()),
                ('diff_srv_rate', models.CharField(max_length=255)),
                ('srv_diff_host_rate', models.CharField(max_length=255)),
                ('dst_host_count', models.IntegerField()),
                ('dst_host_srv_count', models.IntegerField()),
                ('dst_host_same_srv_rate', models.CharField(max_length=255)),
                ('dst_host_diff_srv_rate', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'trace_result',
                'managed': False,
            },
        ),
    ]
